### ISSUE TITLE
Use autoderef specializations

### ISSUE THREAD

**Issue by carbotaniuman** [dimpolo/partialdebug#1]
This could make the crate work on stable, and given a macro is used already, there should be no harm.

**Comment by dimpolo** [comment]
Thanks for the suggestion.
After looking at "fake" specialization methods I settled with inherent method prioritization.
I'll leave the [PR](https://github.com/dimpolo/partialdebug/pull/2) open for a while in case you have any comments and publish a new version soon after.

Note that "fake" specializations have some [caveats](https://github.com/dimpolo/partialdebug/tree/no_specialization#caveats) around generics.

**Comment by dimpolo** [comment]
Done 😁 a56f514aea4b4b5f94ab1c47debd374b44899f22
